### ISSUE TITLE
GUI Feature

### ISSUE THREAD

**Issue by wroersma** [AlbinoGeek/sc2-rsu#8]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I find it annoying to use a CLI when a GUI would make it nice and pleb level for me :)

**Describe the solution you'd like**
I would like a nice GUI to interact with the application because I'm too lazy to use the CLI.

**Comment by AlbinoGeek** [comment]
Sounds like a plan 👍🏻

**Comment by AlbinoGeek** [comment]
Done with #9
